spring:
  datasource:
    url:
    username:
    password:
  redis:
    host:
    database:
  messages:
    basename: i18n/messages



mail:
  host:
  username:
  password:
  from:

file-system:
  mode:
  local:
  aliyun-oss:
    end-point:
    bucket-name:
    data-path:

aliyun:
  access-key-id:
  access-key-secret: